# Imagem base enxuta
FROM python:3.12-slim

# Variáveis de ambiente (boas práticas)
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

# Define diretório de trabalho
WORKDIR /app

# Atualiza pip antes de instalar dependências
RUN pip install --upgrade pip

# Copia apenas o requirements primeiro (melhora cache)
COPY requirements.txt .

# Instala dependências
RUN pip install --no-cache-dir -r requirements.txt

# Copia restante do projeto
COPY . .

# Cria usuário não-root (segurança)
RUN adduser --disabled-password --gecos "" appuser && \
    chown -R appuser /app

USER appuser

# Comando padrão
CMD ["python", "extrair_dados_2.py"]